version: '2'

services:
  producer:
    build:
      context: ./src/Akka.Streams.Kafka.Reproduction.Producer
      dockerfile: Dockerfile
    environment:
      KAFKA_HOST: ""
      KAFKA_PORT: ""
      KAFKA_SASL_USERNAME: ""
      KAFKA_SASL_PASSWORD: ""

  consumer:
    build:
      context: ./src/Akka.Streams.Kafka.Reproduction.SubstreamConsumer
      dockerfile: Dockerfile
    environment:
      KAFKA_HOST: ""
      KAFKA_PORT: ""
      KAFKA_SASL_USERNAME: ""
      KAFKA_SASL_PASSWORD: ""